/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_fenetre_inscription (void);
GtkWidget* create_fenetre_acceuil (void);
GtkWidget* create_authentification (void);
GtkWidget* create_felecitations (void);
GtkWidget* create_espace_client (void);
GtkWidget* create_fenetre_suppcompte (void);
GtkWidget* create_fenetre_modifier (void);
GtkWidget* create_fenetre_affich (void);
