/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_fenetre_inscription (void)
{
  GtkWidget *fenetre_inscription;
  GtkWidget *fixed1;
  GtkWidget *entrynom;
  GtkWidget *entryprenom;
  GtkObject *jour_adj;
  GtkWidget *jour;
  GtkObject *mois_adj;
  GtkWidget *mois;
  GtkObject *annee_adj;
  GtkWidget *annee;
  GtkWidget *entryadresse;
  GtkWidget *entryemail;
  GtkWidget *entrymotdepasse;
  GtkWidget *entrymotdepasse1;
  GtkWidget *erreur;
  GtkWidget *erreur2;
  GtkWidget *erreur4;
  GtkWidget *combobox2;
  GtkWidget *erreur5;
  GtkWidget *buttoninscription;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label536;
  GtkWidget *erreur3;
  GtkWidget *combobox1;
  GtkWidget *entrycin;
  GtkWidget *label527;
  GtkWidget *label528;
  GtkWidget *label529;
  GtkWidget *label531;
  GtkWidget *label530;
  GtkWidget *label526;
  GtkWidget *label525;
  GtkWidget *label524;
  GtkWidget *label523;
  GtkWidget *label532;
  GtkWidget *label533;
  GtkWidget *label534;
  GtkWidget *buttonretour;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label535;
  GtkWidget *erreur1;
  GtkWidget *label1;
  GtkWidget *image18;

  fenetre_inscription = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (fenetre_inscription, 500, 500);
  gtk_window_set_title (GTK_WINDOW (fenetre_inscription), _("Inscription"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (fenetre_inscription), fixed1);

  entrynom = gtk_entry_new ();
  gtk_widget_show (entrynom);
  gtk_fixed_put (GTK_FIXED (fixed1), entrynom, 208, 56);
  gtk_widget_set_size_request (entrynom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynom), 8226);

  entryprenom = gtk_entry_new ();
  gtk_widget_show (entryprenom);
  gtk_fixed_put (GTK_FIXED (fixed1), entryprenom, 208, 104);
  gtk_widget_set_size_request (entryprenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenom), 8226);

  jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour = gtk_spin_button_new (GTK_ADJUSTMENT (jour_adj), 1, 0);
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed1), jour, 288, 256);
  gtk_widget_set_size_request (jour, 60, 27);

  mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois = gtk_spin_button_new (GTK_ADJUSTMENT (mois_adj), 1, 0);
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed1), mois, 416, 256);
  gtk_widget_set_size_request (mois, 60, 27);

  annee_adj = gtk_adjustment_new (1, 1920, 2001, 1, 10, 10);
  annee = gtk_spin_button_new (GTK_ADJUSTMENT (annee_adj), 1, 0);
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed1), annee, 552, 256);
  gtk_widget_set_size_request (annee, 60, 27);

  entryadresse = gtk_entry_new ();
  gtk_widget_show (entryadresse);
  gtk_fixed_put (GTK_FIXED (fixed1), entryadresse, 216, 376);
  gtk_widget_set_size_request (entryadresse, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryadresse), 8226);

  entryemail = gtk_entry_new ();
  gtk_widget_show (entryemail);
  gtk_fixed_put (GTK_FIXED (fixed1), entryemail, 216, 424);
  gtk_widget_set_size_request (entryemail, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryemail), 8226);

  entrymotdepasse = gtk_entry_new ();
  gtk_widget_show (entrymotdepasse);
  gtk_fixed_put (GTK_FIXED (fixed1), entrymotdepasse, 216, 472);
  gtk_widget_set_size_request (entrymotdepasse, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entrymotdepasse), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymotdepasse), 8226);

  entrymotdepasse1 = gtk_entry_new ();
  gtk_widget_show (entrymotdepasse1);
  gtk_fixed_put (GTK_FIXED (fixed1), entrymotdepasse1, 216, 520);
  gtk_widget_set_size_request (entrymotdepasse1, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entrymotdepasse1), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymotdepasse1), 8226);

  erreur = gtk_label_new ("");
  gtk_widget_show (erreur);
  gtk_fixed_put (GTK_FIXED (fixed1), erreur, 416, 520);
  gtk_widget_set_size_request (erreur, 392, 48);

  erreur2 = gtk_label_new ("");
  gtk_widget_show (erreur2);
  gtk_fixed_put (GTK_FIXED (fixed1), erreur2, 376, 144);
  gtk_widget_set_size_request (erreur2, 224, 32);

  erreur4 = gtk_label_new ("");
  gtk_widget_show (erreur4);
  gtk_fixed_put (GTK_FIXED (fixed1), erreur4, 392, 424);
  gtk_widget_set_size_request (erreur4, 392, 32);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed1), combobox2, 216, 320);
  gtk_widget_set_size_request (combobox2, 97, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Male"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Femelle"));

  erreur5 = gtk_label_new ("");
  gtk_widget_show (erreur5);
  gtk_fixed_put (GTK_FIXED (fixed1), erreur5, 376, 456);
  gtk_widget_set_size_request (erreur5, 360, 40);

  buttoninscription = gtk_button_new ();
  gtk_widget_show (buttoninscription);
  gtk_fixed_put (GTK_FIXED (fixed1), buttoninscription, 824, 600);
  gtk_widget_set_size_request (buttoninscription, 146, 64);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttoninscription), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label536 = gtk_label_new_with_mnemonic (_("<span  color=\"black\"><b>M'inscrire</b> </span>\n"));
  gtk_widget_show (label536);
  gtk_box_pack_start (GTK_BOX (hbox1), label536, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label536, 97, 25);
  gtk_label_set_use_markup (GTK_LABEL (label536), TRUE);

  erreur3 = gtk_label_new ("");
  gtk_widget_show (erreur3);
  gtk_fixed_put (GTK_FIXED (fixed1), erreur3, 392, 376);
  gtk_widget_set_size_request (erreur3, 360, 32);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed1), combobox1, 208, 152);
  gtk_widget_set_size_request (combobox1, 161, 32);
  gtk_container_set_border_width (GTK_CONTAINER (combobox1), 1);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Afrique du Sud"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Alg\303\251rie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Angola"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("B\303\251nin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Botswana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Burkina"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Burundi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Cameroun"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Cap-Vert"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("R\303\251publique centrafricaine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Comores"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Congo"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("R\303\251publique d\303\251mocratique du Congo"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("C\303\264te d'Ivoire"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Djibouti"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("\303\211gypte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("\303\211rythr\303\251e"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("\303\211thiopie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Gabon"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Gambie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Ghana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Guin\303\251e"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Guin\303\251e-Bissau"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Guin\303\251e \303\251quatoriale"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Kenya"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Lesotho"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Lib\303\251ria"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Libye"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Madagascar"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Malawi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Mali"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Maroc"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Maurice"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Mauritanie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Mozambique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Namibie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Niger"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Nigeria"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Ouganda"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Rwanda"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Sao Tom\303\251-et-Principe"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("S\303\251n\303\251gal"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Seychelles"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Sierra Leone"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Somalie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Soudan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Sud-Soudan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Swaziland"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Tanzanie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Tchad"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Togo"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Tunisie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Zambie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Zimbabwe"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Antigua-et-Barbuda"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Argentine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Bahamas"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Barbade"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Belize"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Bolivie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Br\303\251sil"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Canada"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Chili"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Colombie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Costa Rica"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Cuba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("R\303\251publique dominicaine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Dominique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("\303\211quateur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("\303\211tats-Unis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Grenade"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Guatemala"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Guyana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Ha\303\257ti"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Honduras"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Jama\303\257que"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Mexique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Nicaragua"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Panama"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Paraguay"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("P\303\251rou"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Porto Rico"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Saint-Christophe-et-Ni\303\251v\303\250s"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Sainte-Lucie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Saint-Vincent-et-les Grenadines"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Salvador"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Suriname"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Trinit\303\251-et-Tobago"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Uruguay"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Venezuela"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Afghanistan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Arabie saoudite"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Bahre\303\257n"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Bangladesh"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Bhoutan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Birmanie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Brunei"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Cambodge"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Chine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Cor\303\251e du Nord"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Cor\303\251e du Sud"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("\303\211mirats arabes unis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Inde"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Indon\303\251sie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Irak"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Iran"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Isra\303\253l"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Japon"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Jordanie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Kazakhstan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Kirghizistan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Kowe\303\257t"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Laos"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Liban"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Malaisie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Maldives"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Mongolie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("N\303\251pal"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Oman"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Ouzb\303\251kistan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Palestine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Pakistan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Philippines"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Qatar"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Singapour"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Sri Lanka"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Syrie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Tadjikistan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Ta\303\257wan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Tha\303\257lande"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Timor oriental"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Turkm\303\251nistan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Turquie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Vi\303\252t Nam"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Y\303\251men"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Allemagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Albanie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Andorre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Arm\303\251nie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Autriche"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Azerba\303\257djan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Belgique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Bi\303\251lorussie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Bosnie-Herz\303\251govine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Bulgarie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Chypre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Croatie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Danemark"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Espagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Estonie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Finlande"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("France"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("G\303\251orgie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Gr\303\250ce"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Hongrie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Irlande"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Islande"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Italie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Lettonie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Liechtenstein"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Lituanie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Luxembourg"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("R\303\251publique de Mac\303\251doine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Malte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Moldavie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Monaco"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Mont\303\251n\303\251gro"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Norv\303\250ge"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Pays-Bas"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Pologne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Portugal"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("R\303\251publique tch\303\250que"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Roumanie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Royaume-Uni"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Russie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Saint-Marin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Serbie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Slovaquie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Slov\303\251nie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Su\303\250de"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Suisse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Ukraine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Vatican"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Australie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Fidji"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Kiribati"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Marshall"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Micron\303\251sie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Nauru"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Nouvelle-Z\303\251lande"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Palaos"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Papouasie-Nouvelle-Guin\303\251e"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Salomon"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Samoa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Tonga"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Tuvalu"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Vanuatu"));

  entrycin = gtk_entry_new ();
  gtk_widget_show (entrycin);
  gtk_fixed_put (GTK_FIXED (fixed1), entrycin, 208, 200);
  gtk_widget_set_size_request (entrycin, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycin), 8226);

  label527 = gtk_label_new_with_mnemonic (_("<span  color=\"blue\"><u>Jous: </u></span>\n"));
  gtk_widget_show (label527);
  gtk_fixed_put (GTK_FIXED (fixed1), label527, 232, 256);
  gtk_widget_set_size_request (label527, 40, 25);
  gtk_label_set_use_markup (GTK_LABEL (label527), TRUE);

  label528 = gtk_label_new_with_mnemonic (_("<span  color=\"blue\"><u>Mois: </u></span>\n"));
  gtk_widget_show (label528);
  gtk_fixed_put (GTK_FIXED (fixed1), label528, 360, 256);
  gtk_widget_set_size_request (label528, 48, 25);
  gtk_label_set_use_markup (GTK_LABEL (label528), TRUE);

  label529 = gtk_label_new_with_mnemonic (_("<span  color=\"blue\"><u>Ann\303\251e: </u></span>\n"));
  gtk_widget_show (label529);
  gtk_fixed_put (GTK_FIXED (fixed1), label529, 488, 256);
  gtk_widget_set_size_request (label529, 56, 24);
  gtk_label_set_use_markup (GTK_LABEL (label529), TRUE);

  label531 = gtk_label_new_with_mnemonic (_("<span  color=\"red\"><u><b>Adresse:</b> </u></span>\n"));
  gtk_widget_show (label531);
  gtk_fixed_put (GTK_FIXED (fixed1), label531, 48, 376);
  gtk_widget_set_size_request (label531, 113, 33);
  gtk_label_set_use_markup (GTK_LABEL (label531), TRUE);

  label530 = gtk_label_new_with_mnemonic (_("<span  color=\"red\"><u><b>Sexe: </b></u></span>\n"));
  gtk_widget_show (label530);
  gtk_fixed_put (GTK_FIXED (fixed1), label530, 48, 312);
  gtk_widget_set_size_request (label530, 121, 41);
  gtk_label_set_use_markup (GTK_LABEL (label530), TRUE);

  label526 = gtk_label_new_with_mnemonic (_("<span  color=\"red\"><u><b>Date de naissance : </b></u></span>\n"));
  gtk_widget_show (label526);
  gtk_fixed_put (GTK_FIXED (fixed1), label526, 24, 248);
  gtk_widget_set_size_request (label526, 137, 41);
  gtk_label_set_use_markup (GTK_LABEL (label526), TRUE);

  label525 = gtk_label_new_with_mnemonic (_("<span  color=\"red\"><u><b>CIN: </b></u></span>\n"));
  gtk_widget_show (label525);
  gtk_fixed_put (GTK_FIXED (fixed1), label525, 48, 200);
  gtk_widget_set_size_request (label525, 72, 25);
  gtk_label_set_use_markup (GTK_LABEL (label525), TRUE);

  label524 = gtk_label_new_with_mnemonic (_("<span  color=\"red\"><u><b>Pays: </b></u></span>\n"));
  gtk_widget_show (label524);
  gtk_fixed_put (GTK_FIXED (fixed1), label524, 16, 152);
  gtk_widget_set_size_request (label524, 113, 33);
  gtk_label_set_use_markup (GTK_LABEL (label524), TRUE);

  label523 = gtk_label_new_with_mnemonic (_("<span  color=\"red\"><u><b>Pr\303\251nom: </b></u></span>\n"));
  gtk_widget_show (label523);
  gtk_fixed_put (GTK_FIXED (fixed1), label523, 32, 104);
  gtk_widget_set_size_request (label523, 105, 33);
  gtk_label_set_use_markup (GTK_LABEL (label523), TRUE);

  label532 = gtk_label_new_with_mnemonic (_("<span  color=\"red\"><u><b>E-mail:</b> </u></span>\n"));
  gtk_widget_show (label532);
  gtk_fixed_put (GTK_FIXED (fixed1), label532, 32, 416);
  gtk_widget_set_size_request (label532, 137, 49);
  gtk_label_set_use_markup (GTK_LABEL (label532), TRUE);

  label533 = gtk_label_new_with_mnemonic (_("<span  color=\"red\"><u><b>Mot de passe :</b> </u></span>\n"));
  gtk_widget_show (label533);
  gtk_fixed_put (GTK_FIXED (fixed1), label533, 40, 456);
  gtk_widget_set_size_request (label533, 136, 57);
  gtk_label_set_use_markup (GTK_LABEL (label533), TRUE);

  label534 = gtk_label_new_with_mnemonic (_("<span  color=\"red\"><u><b>Veuillez confirmer \nvotre mot de passe:</b> </u></span>\n"));
  gtk_widget_show (label534);
  gtk_fixed_put (GTK_FIXED (fixed1), label534, 8, 512);
  gtk_widget_set_size_request (label534, 184, 48);
  gtk_label_set_use_markup (GTK_LABEL (label534), TRUE);

  buttonretour = gtk_button_new ();
  gtk_widget_show (buttonretour);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonretour, 56, 600);
  gtk_widget_set_size_request (buttonretour, 120, 64);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonretour), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label535 = gtk_label_new_with_mnemonic (_("<span  color=\"black\"><b>Retour</b> </span>\n"));
  gtk_widget_show (label535);
  gtk_box_pack_start (GTK_BOX (hbox2), label535, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label535, 97, 25);
  gtk_label_set_use_markup (GTK_LABEL (label535), TRUE);

  erreur1 = gtk_label_new ("");
  gtk_widget_show (erreur1);
  gtk_fixed_put (GTK_FIXED (fixed1), erreur1, 392, 88);
  gtk_widget_set_size_request (erreur1, 352, 40);

  label1 = gtk_label_new_with_mnemonic (_("<span  color=\"red\"><u><b>Nom:</b> </u></span>\n"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 32, 56);
  gtk_widget_set_size_request (label1, 97, 25);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  image18 = create_pixmap (fenetre_inscription, "strong-authentication-article.jpg");
  gtk_widget_show (image18);
  gtk_fixed_put (GTK_FIXED (fixed1), image18, 912, 8);
  gtk_widget_set_size_request (image18, 288, 232);

  g_signal_connect ((gpointer) buttoninscription, "clicked",
                    G_CALLBACK (on_buttoninscription_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretour, "clicked",
                    G_CALLBACK (on_buttonretour_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label527), entrynom);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label528), entrynom);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label529), entrynom);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label531), entrynom);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label530), entrynom);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label526), entrynom);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label525), entrynom);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label524), entrynom);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label523), entrynom);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label532), entrynom);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label533), entrynom);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label534), entrynom);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label1), entrynom);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_inscription, fenetre_inscription, "fenetre_inscription");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, entrynom, "entrynom");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, entryprenom, "entryprenom");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, jour, "jour");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, mois, "mois");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, annee, "annee");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, entryadresse, "entryadresse");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, entryemail, "entryemail");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, entrymotdepasse, "entrymotdepasse");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, entrymotdepasse1, "entrymotdepasse1");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, erreur, "erreur");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, erreur2, "erreur2");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, erreur4, "erreur4");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, erreur5, "erreur5");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, buttoninscription, "buttoninscription");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, image1, "image1");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, label536, "label536");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, erreur3, "erreur3");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, entrycin, "entrycin");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, label527, "label527");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, label528, "label528");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, label529, "label529");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, label531, "label531");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, label530, "label530");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, label526, "label526");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, label525, "label525");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, label524, "label524");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, label523, "label523");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, label532, "label532");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, label533, "label533");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, label534, "label534");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, buttonretour, "buttonretour");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, image2, "image2");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, label535, "label535");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, erreur1, "erreur1");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, label1, "label1");
  GLADE_HOOKUP_OBJECT (fenetre_inscription, image18, "image18");

  return fenetre_inscription;
}

GtkWidget*
create_fenetre_acceuil (void)
{
  GtkWidget *fenetre_acceuil;
  GtkWidget *fixed2;
  GtkWidget *button3;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image13;
  GtkWidget *label539;
  GtkWidget *buttoninscription1;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image12;
  GtkWidget *label538;
  GtkWidget *button1;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image11;
  GtkWidget *label537;
  GtkWidget *image14;

  fenetre_acceuil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (fenetre_acceuil, 500, 250);
  gtk_window_set_title (GTK_WINDOW (fenetre_acceuil), _("Acceuil"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (fenetre_acceuil), fixed2);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3, 400, 528);
  gtk_widget_set_size_request (button3, 352, 104);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button3), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image13 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox12), image13, FALSE, FALSE, 0);

  label539 = gtk_label_new_with_mnemonic (_("<b>Catalogue</b>"));
  gtk_widget_show (label539);
  gtk_box_pack_start (GTK_BOX (hbox12), label539, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label539), TRUE);

  buttoninscription1 = gtk_button_new ();
  gtk_widget_show (buttoninscription1);
  gtk_fixed_put (GTK_FIXED (fixed2), buttoninscription1, 408, 368);
  gtk_widget_set_size_request (buttoninscription1, 344, 104);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (buttoninscription1), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image12 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox11), image12, FALSE, FALSE, 0);

  label538 = gtk_label_new_with_mnemonic (_("<b>Inscription</b>"));
  gtk_widget_show (label538);
  gtk_box_pack_start (GTK_BOX (hbox11), label538, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label538), TRUE);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed2), button1, 408, 240);
  gtk_widget_set_size_request (button1, 344, 96);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button1), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image11 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox10), image11, FALSE, FALSE, 0);

  label537 = gtk_label_new_with_mnemonic (_("<b>Connexion</b>"));
  gtk_widget_show (label537);
  gtk_box_pack_start (GTK_BOX (hbox10), label537, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label537), TRUE);

  image14 = create_pixmap (fenetre_acceuil, "sky-travel-logo.jpg");
  gtk_widget_show (image14);
  gtk_fixed_put (GTK_FIXED (fixed2), image14, 336, 32);
  gtk_widget_set_size_request (image14, 520, 117);

  g_signal_connect ((gpointer) buttoninscription1, "clicked",
                    G_CALLBACK (on_buttoninscription1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_acceuil, fenetre_acceuil, "fenetre_acceuil");
  GLADE_HOOKUP_OBJECT (fenetre_acceuil, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (fenetre_acceuil, button3, "button3");
  GLADE_HOOKUP_OBJECT (fenetre_acceuil, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (fenetre_acceuil, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (fenetre_acceuil, image13, "image13");
  GLADE_HOOKUP_OBJECT (fenetre_acceuil, label539, "label539");
  GLADE_HOOKUP_OBJECT (fenetre_acceuil, buttoninscription1, "buttoninscription1");
  GLADE_HOOKUP_OBJECT (fenetre_acceuil, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (fenetre_acceuil, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (fenetre_acceuil, image12, "image12");
  GLADE_HOOKUP_OBJECT (fenetre_acceuil, label538, "label538");
  GLADE_HOOKUP_OBJECT (fenetre_acceuil, button1, "button1");
  GLADE_HOOKUP_OBJECT (fenetre_acceuil, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (fenetre_acceuil, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (fenetre_acceuil, image11, "image11");
  GLADE_HOOKUP_OBJECT (fenetre_acceuil, label537, "label537");
  GLADE_HOOKUP_OBJECT (fenetre_acceuil, image14, "image14");

  return fenetre_acceuil;
}

GtkWidget*
create_authentification (void)
{
  GtkWidget *authentification;
  GtkWidget *fixed3;
  GtkWidget *entrycin;
  GtkWidget *entrypassword;
  GtkWidget *button5;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label16;
  GtkWidget *label541;
  GtkWidget *label540;
  GtkWidget *meconnecter;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image17;
  GtkWidget *label542;
  GtkWidget *image16;
  GtkWidget *label25;

  authentification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (authentification), _("Se connecter"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (authentification), fixed3);

  entrycin = gtk_entry_new ();
  gtk_widget_show (entrycin);
  gtk_fixed_put (GTK_FIXED (fixed3), entrycin, 576, 288);
  gtk_widget_set_size_request (entrycin, 200, 43);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycin), 8226);

  entrypassword = gtk_entry_new ();
  gtk_widget_show (entrypassword);
  gtk_fixed_put (GTK_FIXED (fixed3), entrypassword, 584, 376);
  gtk_widget_set_size_request (entrypassword, 192, 43);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrypassword), 8226);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed3), button5, 320, 472);
  gtk_widget_set_size_request (button5, 138, 61);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button5), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("<b>Acceuil</b>"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox3), label16, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  label541 = gtk_label_new_with_mnemonic (_("<span  color=\"red\"><u><b>Mot de passe:</b> </u></span>\n"));
  gtk_widget_show (label541);
  gtk_fixed_put (GTK_FIXED (fixed3), label541, 312, 360);
  gtk_widget_set_size_request (label541, 208, 88);
  gtk_label_set_use_markup (GTK_LABEL (label541), TRUE);

  label540 = gtk_label_new_with_mnemonic (_("<span  color=\"red\"><u><b>Identifiant(N\302\260CIN)</b> </u></span>\n"));
  gtk_widget_show (label540);
  gtk_fixed_put (GTK_FIXED (fixed3), label540, 320, 280);
  gtk_widget_set_size_request (label540, 192, 65);
  gtk_label_set_use_markup (GTK_LABEL (label540), TRUE);

  meconnecter = gtk_button_new ();
  gtk_widget_show (meconnecter);
  gtk_fixed_put (GTK_FIXED (fixed3), meconnecter, 632, 464);
  gtk_widget_set_size_request (meconnecter, 146, 64);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (meconnecter), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image17 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox13), image17, FALSE, FALSE, 0);

  label542 = gtk_label_new_with_mnemonic (_("<b>Me connecter</b>"));
  gtk_widget_show (label542);
  gtk_box_pack_start (GTK_BOX (hbox13), label542, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label542), TRUE);

  image16 = create_pixmap (authentification, "index.jpeg");
  gtk_widget_show (image16);
  gtk_fixed_put (GTK_FIXED (fixed3), image16, 344, 0);
  gtk_widget_set_size_request (image16, 432, 272);

  label25 = gtk_label_new ("");
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed3), label25, 40, 128);
  gtk_widget_set_size_request (label25, 288, 64);

  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) meconnecter, "clicked",
                    G_CALLBACK (on_meconnecter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (authentification, authentification, "authentification");
  GLADE_HOOKUP_OBJECT (authentification, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (authentification, entrycin, "entrycin");
  GLADE_HOOKUP_OBJECT (authentification, entrypassword, "entrypassword");
  GLADE_HOOKUP_OBJECT (authentification, button5, "button5");
  GLADE_HOOKUP_OBJECT (authentification, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (authentification, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (authentification, image3, "image3");
  GLADE_HOOKUP_OBJECT (authentification, label16, "label16");
  GLADE_HOOKUP_OBJECT (authentification, label541, "label541");
  GLADE_HOOKUP_OBJECT (authentification, label540, "label540");
  GLADE_HOOKUP_OBJECT (authentification, meconnecter, "meconnecter");
  GLADE_HOOKUP_OBJECT (authentification, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (authentification, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (authentification, image17, "image17");
  GLADE_HOOKUP_OBJECT (authentification, label542, "label542");
  GLADE_HOOKUP_OBJECT (authentification, image16, "image16");
  GLADE_HOOKUP_OBJECT (authentification, label25, "label25");

  return authentification;
}

GtkWidget*
create_felecitations (void)
{
  GtkWidget *felecitations;
  GtkWidget *fixed4;
  GtkWidget *button6;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label544;
  GtkWidget *label543;

  felecitations = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (felecitations), _("window2"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (felecitations), fixed4);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed4), button6, 416, 272);
  gtk_widget_set_size_request (button6, 264, 88);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button6), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label544 = gtk_label_new_with_mnemonic (_("<b>Me connecter</b> "));
  gtk_widget_show (label544);
  gtk_box_pack_start (GTK_BOX (hbox4), label544, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label544, 97, 25);
  gtk_label_set_use_markup (GTK_LABEL (label544), TRUE);

  label543 = gtk_label_new_with_mnemonic (_("<span  color=\"black\"><u><b>F\303\251licitation,votre compte a \303\251t\303\251\n cr\303\251e avec succ\303\251s</b> </u></span>\n"));
  gtk_widget_show (label543);
  gtk_fixed_put (GTK_FIXED (fixed4), label543, 64, 88);
  gtk_widget_set_size_request (label543, 848, 200);
  gtk_label_set_use_markup (GTK_LABEL (label543), TRUE);

  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (felecitations, felecitations, "felecitations");
  GLADE_HOOKUP_OBJECT (felecitations, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (felecitations, button6, "button6");
  GLADE_HOOKUP_OBJECT (felecitations, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (felecitations, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (felecitations, image4, "image4");
  GLADE_HOOKUP_OBJECT (felecitations, label544, "label544");
  GLADE_HOOKUP_OBJECT (felecitations, label543, "label543");

  return felecitations;
}

GtkWidget*
create_espace_client (void)
{
  GtkWidget *espace_client;
  GtkWidget *fixed5;
  GtkWidget *deconnexion;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label24;
  GtkWidget *notebook1;
  GtkWidget *fixed6;
  GtkWidget *image26;
  GtkWidget *image27;
  GtkWidget *afficher;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image22;
  GtkWidget *label564;
  GtkWidget *buttonsupprimer;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image20;
  GtkWidget *label545;
  GtkWidget *button777;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image21;
  GtkWidget *label546;
  GtkWidget *label23;

  espace_client = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (espace_client), _("windowespaceclient"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (espace_client), fixed5);

  deconnexion = gtk_button_new ();
  gtk_widget_show (deconnexion);
  gtk_fixed_put (GTK_FIXED (fixed5), deconnexion, 672, 0);
  gtk_widget_set_size_request (deconnexion, 146, 56);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (deconnexion), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("<b>Me deconnecter</b>"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox5), label24, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed5), notebook1, 8, 32);
  gtk_widget_set_size_request (notebook1, 824, 464);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  image26 = create_pixmap (espace_client, "travel-editor-favorite-products.jpg");
  gtk_widget_show (image26);
  gtk_fixed_put (GTK_FIXED (fixed6), image26, 352, 112);
  gtk_widget_set_size_request (image26, 21, 21);

  image27 = create_pixmap (espace_client, "why-choose-summary.jpg");
  gtk_widget_show (image27);
  gtk_fixed_put (GTK_FIXED (fixed6), image27, 0, 0);
  gtk_widget_set_size_request (image27, 848, 320);

  afficher = gtk_button_new ();
  gtk_widget_show (afficher);
  gtk_fixed_put (GTK_FIXED (fixed6), afficher, 72, 232);
  gtk_widget_set_size_request (afficher, 192, 80);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (afficher), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image22 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox16), image22, FALSE, FALSE, 0);

  label564 = gtk_label_new_with_mnemonic (_("<b>Afficher mon\n     compte</b>"));
  gtk_widget_show (label564);
  gtk_box_pack_start (GTK_BOX (hbox16), label564, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label564), TRUE);

  buttonsupprimer = gtk_button_new ();
  gtk_widget_show (buttonsupprimer);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonsupprimer, 304, 240);
  gtk_widget_set_size_request (buttonsupprimer, 216, 72);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (buttonsupprimer), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image20 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox14), image20, FALSE, FALSE, 0);

  label545 = gtk_label_new_with_mnemonic (_("<b>Supprimer mon compte</b>"));
  gtk_widget_show (label545);
  gtk_box_pack_start (GTK_BOX (hbox14), label545, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label545), TRUE);

  button777 = gtk_button_new ();
  gtk_widget_show (button777);
  gtk_fixed_put (GTK_FIXED (fixed6), button777, 568, 248);
  gtk_widget_set_size_request (button777, 192, 61);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button777), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image21 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox15), image21, FALSE, FALSE, 0);

  label546 = gtk_label_new_with_mnemonic (_("<b>Modifier mon compte</b>"));
  gtk_widget_show (label546);
  gtk_box_pack_start (GTK_BOX (hbox15), label546, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label546), TRUE);

  label23 = gtk_label_new (_("<b>Mon compte</b>"));
  gtk_widget_show (label23);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label23);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);

  g_signal_connect ((gpointer) deconnexion, "clicked",
                    G_CALLBACK (on_deconnexion_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher, "clicked",
                    G_CALLBACK (on_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonsupprimer, "clicked",
                    G_CALLBACK (on_buttonsupprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button777, "clicked",
                    G_CALLBACK (on_button777_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (espace_client, espace_client, "espace_client");
  GLADE_HOOKUP_OBJECT (espace_client, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (espace_client, deconnexion, "deconnexion");
  GLADE_HOOKUP_OBJECT (espace_client, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (espace_client, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (espace_client, image5, "image5");
  GLADE_HOOKUP_OBJECT (espace_client, label24, "label24");
  GLADE_HOOKUP_OBJECT (espace_client, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (espace_client, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (espace_client, image26, "image26");
  GLADE_HOOKUP_OBJECT (espace_client, image27, "image27");
  GLADE_HOOKUP_OBJECT (espace_client, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (espace_client, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (espace_client, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (espace_client, image22, "image22");
  GLADE_HOOKUP_OBJECT (espace_client, label564, "label564");
  GLADE_HOOKUP_OBJECT (espace_client, buttonsupprimer, "buttonsupprimer");
  GLADE_HOOKUP_OBJECT (espace_client, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (espace_client, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (espace_client, image20, "image20");
  GLADE_HOOKUP_OBJECT (espace_client, label545, "label545");
  GLADE_HOOKUP_OBJECT (espace_client, button777, "button777");
  GLADE_HOOKUP_OBJECT (espace_client, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (espace_client, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (espace_client, image21, "image21");
  GLADE_HOOKUP_OBJECT (espace_client, label546, "label546");
  GLADE_HOOKUP_OBJECT (espace_client, label23, "label23");

  return espace_client;
}

GtkWidget*
create_fenetre_suppcompte (void)
{
  GtkWidget *fenetre_suppcompte;
  GtkWidget *fixed7;
  GtkWidget *entrycin1;
  GtkWidget *entrymotdepasse1;
  GtkWidget *label548;
  GtkWidget *label549;
  GtkWidget *button8;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image23;
  GtkWidget *label550;
  GtkWidget *buttondesactivercompte1;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image24;
  GtkWidget *label551;
  GtkWidget *desactlabel;

  fenetre_suppcompte = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_suppcompte), _("Desactiver mon compte"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (fenetre_suppcompte), fixed7);

  entrycin1 = gtk_entry_new ();
  gtk_widget_show (entrycin1);
  gtk_fixed_put (GTK_FIXED (fixed7), entrycin1, 144, 88);
  gtk_widget_set_size_request (entrycin1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycin1), 8226);

  entrymotdepasse1 = gtk_entry_new ();
  gtk_widget_show (entrymotdepasse1);
  gtk_fixed_put (GTK_FIXED (fixed7), entrymotdepasse1, 144, 144);
  gtk_widget_set_size_request (entrymotdepasse1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymotdepasse1), 8226);

  label548 = gtk_label_new_with_mnemonic (_("<span  color=\"red\"><u><b>E-mail:</b> </u></span>\n"));
  gtk_widget_show (label548);
  gtk_fixed_put (GTK_FIXED (fixed7), label548, 40, 80);
  gtk_widget_set_size_request (label548, 80, 25);
  gtk_label_set_use_markup (GTK_LABEL (label548), TRUE);

  label549 = gtk_label_new_with_mnemonic (_("<span  color=\"red\"><u><b>Mot de passe :</b> </u></span>\n"));
  gtk_widget_show (label549);
  gtk_fixed_put (GTK_FIXED (fixed7), label549, 16, 136);
  gtk_widget_set_size_request (label549, 128, 40);
  gtk_label_set_use_markup (GTK_LABEL (label549), TRUE);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed7), button8, 16, 264);
  gtk_widget_set_size_request (button8, 130, 53);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button8), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image23 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox17), image23, FALSE, FALSE, 0);

  label550 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label550);
  gtk_box_pack_start (GTK_BOX (hbox17), label550, FALSE, FALSE, 0);

  buttondesactivercompte1 = gtk_button_new ();
  gtk_widget_show (buttondesactivercompte1);
  gtk_fixed_put (GTK_FIXED (fixed7), buttondesactivercompte1, 240, 256);
  gtk_widget_set_size_request (buttondesactivercompte1, 122, 56);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (buttondesactivercompte1), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image24 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox18), image24, FALSE, FALSE, 0);

  label551 = gtk_label_new_with_mnemonic (_("Desactiver"));
  gtk_widget_show (label551);
  gtk_box_pack_start (GTK_BOX (hbox18), label551, FALSE, FALSE, 0);

  desactlabel = gtk_label_new ("");
  gtk_widget_show (desactlabel);
  gtk_fixed_put (GTK_FIXED (fixed7), desactlabel, 80, 200);
  gtk_widget_set_size_request (desactlabel, 320, 48);

  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_button8_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttondesactivercompte1, "clicked",
                    G_CALLBACK (on_buttondesactivercompte1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_suppcompte, fenetre_suppcompte, "fenetre_suppcompte");
  GLADE_HOOKUP_OBJECT (fenetre_suppcompte, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (fenetre_suppcompte, entrycin1, "entrycin1");
  GLADE_HOOKUP_OBJECT (fenetre_suppcompte, entrymotdepasse1, "entrymotdepasse1");
  GLADE_HOOKUP_OBJECT (fenetre_suppcompte, label548, "label548");
  GLADE_HOOKUP_OBJECT (fenetre_suppcompte, label549, "label549");
  GLADE_HOOKUP_OBJECT (fenetre_suppcompte, button8, "button8");
  GLADE_HOOKUP_OBJECT (fenetre_suppcompte, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (fenetre_suppcompte, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (fenetre_suppcompte, image23, "image23");
  GLADE_HOOKUP_OBJECT (fenetre_suppcompte, label550, "label550");
  GLADE_HOOKUP_OBJECT (fenetre_suppcompte, buttondesactivercompte1, "buttondesactivercompte1");
  GLADE_HOOKUP_OBJECT (fenetre_suppcompte, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (fenetre_suppcompte, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (fenetre_suppcompte, image24, "image24");
  GLADE_HOOKUP_OBJECT (fenetre_suppcompte, label551, "label551");
  GLADE_HOOKUP_OBJECT (fenetre_suppcompte, desactlabel, "desactlabel");

  return fenetre_suppcompte;
}

GtkWidget*
create_fenetre_modifier (void)
{
  GtkWidget *fenetre_modifier;
  GtkWidget *fixed8;
  GtkWidget *entrynom10;
  GtkObject *jour10_adj;
  GtkWidget *jour10;
  GtkObject *mois10_adj;
  GtkWidget *mois10;
  GtkObject *annee10_adj;
  GtkWidget *annee10;
  GtkWidget *entryadresse10;
  GtkWidget *entrycin10;
  GtkWidget *entrymotdepasse10;
  GtkWidget *button999;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label505;
  GtkWidget *buttonmodifierclients;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label504;
  GtkWidget *entryprenom100;
  GtkWidget *combobox444;
  GtkWidget *combobox333;
  GtkWidget *label552;
  GtkWidget *label553;
  GtkWidget *label554;
  GtkWidget *label556;
  GtkWidget *label557;
  GtkWidget *label558;
  GtkWidget *label555;
  GtkWidget *label559;
  GtkWidget *label560;
  GtkWidget *label561;
  GtkWidget *label562;

  fenetre_modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_modifier), _("Modifier mon compte"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (fenetre_modifier), fixed8);

  entrynom10 = gtk_entry_new ();
  gtk_widget_show (entrynom10);
  gtk_fixed_put (GTK_FIXED (fixed8), entrynom10, 144, 32);
  gtk_widget_set_size_request (entrynom10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynom10), 8226);

  jour10_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour10 = gtk_spin_button_new (GTK_ADJUSTMENT (jour10_adj), 1, 0);
  gtk_widget_show (jour10);
  gtk_fixed_put (GTK_FIXED (fixed8), jour10, 232, 184);
  gtk_widget_set_size_request (jour10, 60, 27);

  mois10_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois10 = gtk_spin_button_new (GTK_ADJUSTMENT (mois10_adj), 1, 0);
  gtk_widget_show (mois10);
  gtk_fixed_put (GTK_FIXED (fixed8), mois10, 376, 184);
  gtk_widget_set_size_request (mois10, 60, 27);

  annee10_adj = gtk_adjustment_new (1920, 1920, 2001, 1, 10, 10);
  annee10 = gtk_spin_button_new (GTK_ADJUSTMENT (annee10_adj), 1, 0);
  gtk_widget_show (annee10);
  gtk_fixed_put (GTK_FIXED (fixed8), annee10, 528, 184);
  gtk_widget_set_size_request (annee10, 60, 27);

  entryadresse10 = gtk_entry_new ();
  gtk_widget_show (entryadresse10);
  gtk_fixed_put (GTK_FIXED (fixed8), entryadresse10, 144, 304);
  gtk_widget_set_size_request (entryadresse10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryadresse10), 8226);

  entrycin10 = gtk_entry_new ();
  gtk_widget_show (entrycin10);
  gtk_fixed_put (GTK_FIXED (fixed8), entrycin10, 144, 344);
  gtk_widget_set_size_request (entrycin10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycin10), 8226);

  entrymotdepasse10 = gtk_entry_new ();
  gtk_widget_show (entrymotdepasse10);
  gtk_fixed_put (GTK_FIXED (fixed8), entrymotdepasse10, 144, 384);
  gtk_widget_set_size_request (entrymotdepasse10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymotdepasse10), 8226);

  button999 = gtk_button_new ();
  gtk_widget_show (button999);
  gtk_fixed_put (GTK_FIXED (fixed8), button999, 48, 496);
  gtk_widget_set_size_request (button999, 138, 69);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button999), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label505 = gtk_label_new_with_mnemonic (_("<b>Retour</b>"));
  gtk_widget_show (label505);
  gtk_box_pack_start (GTK_BOX (hbox7), label505, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label505), TRUE);

  buttonmodifierclients = gtk_button_new ();
  gtk_widget_show (buttonmodifierclients);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonmodifierclients, 576, 496);
  gtk_widget_set_size_request (buttonmodifierclients, 130, 72);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttonmodifierclients), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label504 = gtk_label_new_with_mnemonic (_("<b>Modifier</b>"));
  gtk_widget_show (label504);
  gtk_box_pack_start (GTK_BOX (hbox6), label504, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label504), TRUE);

  entryprenom100 = gtk_entry_new ();
  gtk_widget_show (entryprenom100);
  gtk_fixed_put (GTK_FIXED (fixed8), entryprenom100, 144, 64);
  gtk_widget_set_size_request (entryprenom100, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenom100), 8226);

  combobox444 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox444);
  gtk_fixed_put (GTK_FIXED (fixed8), combobox444, 152, 248);
  gtk_widget_set_size_request (combobox444, 152, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox444), _("Male"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox444), _("Femelle"));

  combobox333 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox333);
  gtk_fixed_put (GTK_FIXED (fixed8), combobox333, 144, 112);
  gtk_widget_set_size_request (combobox333, 144, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Tunisie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Afrique du Sud"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Alg\303\251rie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Angola"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("B\303\251nin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Botswana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Burkina"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Burundi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Cameroun"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Cap-Vert"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("R\303\251publique centrafricaine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Comores"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Congo"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("R\303\251publique d\303\251mocratique du Congo"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("C\303\264te d'Ivoire"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Djibouti"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("\303\211gypte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("\303\211rythr\303\251e"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("\303\211thiopie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Gabon"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Gambie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Ghana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Guin\303\251e"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Guin\303\251e-Bissau"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Guin\303\251e \303\251quatoriale"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Kenya"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Lesotho"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Lib\303\251ria"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Libye"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Madagascar"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Malawi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Mali"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Maroc"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Maurice"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Mauritanie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Mozambique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Namibie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Niger"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Nigeria"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Ouganda"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Rwanda"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Sao Tom\303\251-et-Principe"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("S\303\251n\303\251gal"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Seychelles"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Sierra Leone"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Somalie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Soudan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Sud-Soudan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Swaziland"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Tanzanie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Tchad"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Togo"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Tunisie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Zambie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Zimbabwe"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Antigua-et-Barbuda"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Argentine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Bahamas"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Barbade"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Belize"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Bolivie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Br\303\251sil"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Canada"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Chili"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Colombie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Costa Rica"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Cuba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("R\303\251publique dominicaine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Dominique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("\303\211quateur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("\303\211tats-Unis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Grenade"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Guatemala"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Guyana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Ha\303\257ti"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Honduras"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Jama\303\257que"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Mexique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Nicaragua"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Panama"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Paraguay"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("P\303\251rou"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Porto Rico"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Saint-Christophe-et-Ni\303\251v\303\250s"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Sainte-Lucie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Saint-Vincent-et-les Grenadines"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Salvador"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Suriname"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Trinit\303\251-et-Tobago"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Uruguay"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Venezuela"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Afghanistan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Arabie saoudite"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Bahre\303\257n"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Bangladesh"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Bhoutan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Birmanie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Brunei"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Cambodge"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Chine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Cor\303\251e du Nord"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Cor\303\251e du Sud"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("\303\211mirats arabes unis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Inde"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Indon\303\251sie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Irak"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Iran"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Isra\303\253l"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Japon"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Jordanie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Kazakhstan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Kirghizistan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Kowe\303\257t"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Laos"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Liban"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Malaisie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Maldives"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Mongolie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("N\303\251pal"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Oman"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Ouzb\303\251kistan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Palestine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Pakistan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Philippines"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Qatar"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Singapour"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Sri Lanka"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Syrie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Tadjikistan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Ta\303\257wan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Tha\303\257lande"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Timor oriental"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Turkm\303\251nistan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Turquie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Vi\303\252t Nam"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Y\303\251men"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Allemagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Albanie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Andorre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Arm\303\251nie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Autriche"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Azerba\303\257djan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Belgique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Bi\303\251lorussie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Bosnie-Herz\303\251govine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Bulgarie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Chypre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Croatie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Danemark"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Espagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Estonie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Finlande"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("France"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("G\303\251orgie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Gr\303\250ce"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Hongrie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Irlande"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Islande"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Italie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Lettonie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Liechtenstein"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Lituanie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Luxembourg"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("R\303\251publique de Mac\303\251doine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Malte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Moldavie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Monaco"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Mont\303\251n\303\251gro"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Norv\303\250ge"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Pays-Bas"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Pologne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Portugal"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("R\303\251publique tch\303\250que"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Roumanie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Royaume-Uni"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Russie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Saint-Marin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Serbie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Slovaquie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Slov\303\251nie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Su\303\250de"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Suisse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Ukraine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Vatican"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Australie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Fidji"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Kiribati"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Marshall"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Micron\303\251sie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Nauru"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Nouvelle-Z\303\251lande"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Palaos"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Papouasie-Nouvelle-Guin\303\251e"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Salomon"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Samoa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Tonga"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Tuvalu"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox333), _("Vanuatu"));

  label552 = gtk_label_new_with_mnemonic (_("<span  color=\"red\"><u><b>Nom:</b> </u></span>\n"));
  gtk_widget_show (label552);
  gtk_fixed_put (GTK_FIXED (fixed8), label552, 40, 32);
  gtk_widget_set_size_request (label552, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label552), TRUE);

  label553 = gtk_label_new_with_mnemonic (_("<span  color=\"red\"><u><b>Pr\303\251nom</b> </u></span>\n"));
  gtk_widget_show (label553);
  gtk_fixed_put (GTK_FIXED (fixed8), label553, 40, 72);
  gtk_widget_set_size_request (label553, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label553), TRUE);

  label554 = gtk_label_new_with_mnemonic (_("<span  color=\"red\"><u><b>Pays:</b> </u></span>\n"));
  gtk_widget_show (label554);
  gtk_fixed_put (GTK_FIXED (fixed8), label554, 40, 120);
  gtk_widget_set_size_request (label554, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label554), TRUE);

  label556 = gtk_label_new_with_mnemonic (_("<span  color=\"blue\"><u><b>Jours:</b> </u></span>\n"));
  gtk_widget_show (label556);
  gtk_fixed_put (GTK_FIXED (fixed8), label556, 160, 184);
  gtk_widget_set_size_request (label556, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label556), TRUE);

  label557 = gtk_label_new_with_mnemonic (_("<span  color=\"blue\"><u><b>Mois:</b> </u></span>\n"));
  gtk_widget_show (label557);
  gtk_fixed_put (GTK_FIXED (fixed8), label557, 312, 184);
  gtk_widget_set_size_request (label557, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label557), TRUE);

  label558 = gtk_label_new_with_mnemonic (_("<span  color=\"blue\"><u><b>Ann\303\251e:</b> </u></span>\n"));
  gtk_widget_show (label558);
  gtk_fixed_put (GTK_FIXED (fixed8), label558, 456, 184);
  gtk_widget_set_size_request (label558, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label558), TRUE);

  label555 = gtk_label_new_with_mnemonic (_("<span  color=\"red\"><u><b>Date de naissance:</b> </u></span>\n"));
  gtk_widget_show (label555);
  gtk_fixed_put (GTK_FIXED (fixed8), label555, 0, 184);
  gtk_widget_set_size_request (label555, 144, 32);
  gtk_label_set_use_markup (GTK_LABEL (label555), TRUE);

  label559 = gtk_label_new_with_mnemonic (_("<span  color=\"red\"><u><b>Pays:</b> </u></span>\n"));
  gtk_widget_show (label559);
  gtk_fixed_put (GTK_FIXED (fixed8), label559, 56, 256);
  gtk_widget_set_size_request (label559, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label559), TRUE);

  label560 = gtk_label_new_with_mnemonic (_("<span  color=\"red\"><u><b>Adresse:</b> </u></span>\n"));
  gtk_widget_show (label560);
  gtk_fixed_put (GTK_FIXED (fixed8), label560, 40, 312);
  gtk_widget_set_size_request (label560, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label560), TRUE);

  label561 = gtk_label_new_with_mnemonic (_("<span  color=\"red\"><u><b>CIN:</b> </u></span>\n"));
  gtk_widget_show (label561);
  gtk_fixed_put (GTK_FIXED (fixed8), label561, 40, 352);
  gtk_widget_set_size_request (label561, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label561), TRUE);

  label562 = gtk_label_new_with_mnemonic (_("<span  color=\"red\"><u><b>Mot de passe :</b> </u></span>\n"));
  gtk_widget_show (label562);
  gtk_fixed_put (GTK_FIXED (fixed8), label562, 16, 384);
  gtk_widget_set_size_request (label562, 129, 25);
  gtk_label_set_use_markup (GTK_LABEL (label562), TRUE);

  g_signal_connect ((gpointer) button999, "clicked",
                    G_CALLBACK (on_button999_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonmodifierclients, "clicked",
                    G_CALLBACK (on_buttonmodifierclients_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label552), entrynom10);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label556), jour10);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label557), mois10);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label558), annee10);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label562), entrymotdepasse10);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_modifier, fenetre_modifier, "fenetre_modifier");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, entrynom10, "entrynom10");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, jour10, "jour10");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, mois10, "mois10");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, annee10, "annee10");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, entryadresse10, "entryadresse10");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, entrycin10, "entrycin10");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, entrymotdepasse10, "entrymotdepasse10");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, button999, "button999");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, image7, "image7");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label505, "label505");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, buttonmodifierclients, "buttonmodifierclients");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, image6, "image6");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label504, "label504");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, entryprenom100, "entryprenom100");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, combobox444, "combobox444");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, combobox333, "combobox333");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label552, "label552");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label553, "label553");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label554, "label554");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label556, "label556");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label557, "label557");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label558, "label558");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label555, "label555");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label559, "label559");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label560, "label560");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label561, "label561");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label562, "label562");

  return fenetre_modifier;
}

GtkWidget*
create_fenetre_affich (void)
{
  GtkWidget *fenetre_affich;
  GtkWidget *fixed9;
  GtkWidget *treeview2;
  GtkWidget *buttonretoureclient;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image25;
  GtkWidget *label563;

  fenetre_affich = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_affich), _("window2"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (fenetre_affich), fixed9);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed9), treeview2, 16, 56);
  gtk_widget_set_size_request (treeview2, 840, 216);

  buttonretoureclient = gtk_button_new ();
  gtk_widget_show (buttonretoureclient);
  gtk_fixed_put (GTK_FIXED (fixed9), buttonretoureclient, 280, 320);
  gtk_widget_set_size_request (buttonretoureclient, 264, 88);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (buttonretoureclient), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image25 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox19), image25, FALSE, FALSE, 0);

  label563 = gtk_label_new_with_mnemonic (_("<b>Retour</b>"));
  gtk_widget_show (label563);
  gtk_box_pack_start (GTK_BOX (hbox19), label563, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label563), TRUE);

  g_signal_connect ((gpointer) buttonretoureclient, "clicked",
                    G_CALLBACK (on_buttonretoureclient_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_affich, fenetre_affich, "fenetre_affich");
  GLADE_HOOKUP_OBJECT (fenetre_affich, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (fenetre_affich, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (fenetre_affich, buttonretoureclient, "buttonretoureclient");
  GLADE_HOOKUP_OBJECT (fenetre_affich, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (fenetre_affich, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (fenetre_affich, image25, "image25");
  GLADE_HOOKUP_OBJECT (fenetre_affich, label563, "label563");

  return fenetre_affich;
}

